### ISSUE TITLE
standalone package?

### ISSUE THREAD

**Issue by paOol** [JDonadio/address-translator#6]
can we get the translation part as a standalone library?

like

`npm i bitpay-address-translator`

then we can just do

```
import bitpay from "bitpay-address-translator";
let test  = bitpay.translate('1AdafAF3gADFgaADF`);
// CTTSV2J53nErMAYViwE4rF5ePfsmW
or 
let another = bitpay.translate('CTTSV2J53nErMAYViwE4rF5ePfsqKLdW');
// 1zDSgaDFawAHa

```

**Comment by JDonadio** [comment]
That would be great, let me consult it with our team and I'll keep you posted. Thanks for your suggestion!

**Comment by paOol** [comment]
https://www.npmjs.com/package/npm-address-translator
