### ISSUE TITLE
Need Help Moving Bitcoin Cash Out of BitPay App

### ISSUE THREAD

**Issue by ghost** [JDonadio/address-translator#8]
### Actual behavior
Cannot move BCH out of BitPay.
Paid fee for no apparent reason.

### Expected behavior
Can move BCH out of BitPay.
Do not pay fee for conversion unnecessarily.

### Steps to reproduce the behavior
1. Attempt to transfer money to valid BCH wallet address.
2. Receive error “Copay only supports Bitcoin Cash using new version numbers addresses“.
3. Click Learn more.
4. Arrive at [support article](https://support.bitpay.com/hc/en-us/articles/115004671663) with this address translator linked.
5. Input destination wallet address and convert with [translator tool](https://bitpay.github.io/address-translator/)
6. Use new destination address in app to send money.
7. Wait for confirmation.
8. Confirm money never moves and balance is reduced.

### Aditional information
Please mention all relevant information you such as:

* App version: BitPay v3.8.6
* Device and OS used: iPhone 6/iOS 11
* Address or transaction id: https://bch-insight.bitpay.com/address/CKq569kL3MULEqTjwY5g1kYt6cciphqJLa

**Comment by JDonadio** [comment]
Hi there, your transaction is confirmed and your balance wasn't updated?

**Comment by ghost** [comment]
Thanks for the quick response, @JDonadio. TBH I'm not even sure if I'm using this thing properly. Basically I'm trying to transfer my BCH balance of about $7 from BitPay to another wallet. My instinct after reviewing the docs was to convert the external wallet address and send the $7 to the converted address.

BCH address I'm trying to send to: 18jVH41u9o8NaLLyrb9QSJvZ79PbdRq81a

**Comment by JDonadio** [comment]
That's correct. Both Copay (or BitPay wallet) as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by JDonadio** [comment]
The translation result:

Original address: `18jVH41u9o8NaLLyrb9QSJvZ79PbdRq81a `
Result address: `CQCNr6My2r6uUUFQYLUL1pYajGc1SNj5aV`

I'm afraid your transaction wasn't sent to your translated address but `CKq569kL3MULEqTjwY5g1kYt6cciphqJLa`.

**Comment by ghost** [comment]
Ah. Right you are @JDonadio. I initiated the transaction again with the result address and the funds appeared in the destination wallet almost instantly. Woohoo! Good stuff. Thanks, buddy.

**Comment by JDonadio** [comment]
Glad to help!
