### ISSUE TITLE
Address Translator not responding

### ISSUE THREAD

**Issue by benrcole** [JDonadio/address-translator#9]
For general questions regarding Copay/BitPay wallet please visit our: 

  * [Wiki section](https://github.com/bitpay/copay/wiki/COPAY---FAQ) 
  * [How To Library on YouTube](https://www.youtube.com/user/BitPayVideos/playlists)

Please describe your issue following this template:

### Actual behavior
Translator doesn't *do* anything once I have entered an old style BCH address

### Expected behaviour

Translator translates address..

### Steps to reproduce the behavior
Navigate to https://bitpay.github.io/address-translator/
Input address
....

### Aditional information
Please mention all relevant information you such as:

Tested in Chrome and Safari on Mac OSX

***
**NOTE**: If you delete this template your issue will be deleted or it could take a long time to be replied.

**Comment by JDonadio** [comment]
Fixed. Thank you very much!
